### ISSUE TITLE
Compiling zippy with Graal

### ISSUE THREAD

**Issue by jjfumero** [securesystemslab/zippy#1]
I am trying to compile zippy with Graal VM. The last version of JVMCI is 0.22 from OTN.
Following the instruction for zippy I should checkout graal-0.15 but it does not compile.

However if I upgrade to the last one (6ea7811a3865d11b6e3660f1bfe03677a4150716), it compiles with no problem. I can compile then zippy but I get many warnings like this:

> /edu.uci.python/src/edu/uci/python/nodes/PNodeUtil.java:32: warning: [deprecation] NodeFieldAccessor in com.oracle.truffle.api.nodes has been deprecated
import com.oracle.truffle.api.nodes.NodeFieldAccessor;

But it seems I can run **mx python**. How could I trace I am using Graal? How could the compilation for a Python method via Partial Evaluation?

**Comment by qunaibit** [comment]
We are in process to update ZipPy to the latest Graal/Truffle. We will update the documentation once our upgrade is complete

**Comment by nimish** [comment]
Hi, has there been any progress?

**Comment by qunaibit** [comment]
Hi,
There will be an update during the upcoming week.. stay tuned :)
