### ISSUE TITLE
PEP 523

### ISSUE THREAD

**Issue by oroppas** [securesystemslab/zippy#2]
Out of curiosity, will Zippy benefit from PEP 523 in Python 3.6?

https://www.python.org/dev/peps/pep-0523/

**Comment by qunaibit** [comment]
Hi,
Sorry for the tardy reply :)
Zippy relies on Truffle/Graal Partial evaluation to JIT hot codes at the AST level based on runtime profiling feedback. Adding a new field to store arbitrary data (as per PEP 523) might be beneficial for profiling and debugging, but we haven't had a chance to implement it yet.

Cheers,

**Comment by oroppas** [comment]
Thanks for the info.

BTW, I wonder how Zippy will address the issues with C extensions (esp. numpy, scipy, etc.)
Jython goes with [JyNI](http://jyni.org/) with [project panama(http://openjdk.java.net/projects/panama/)

JRuby explores [Graal + Truffle and Sulong](http://chrisseaton.com/rubytruffle/llvm-cauldron-16/llvm-cauldron-sulong.pdf).

It's still not clear to me how Graal & Truffle can address the issue of API design, GC, GIL, etc.
Can Zippy take the same path as JRuby with Sulong?

**Comment by qunaibit** [comment]
Our plan is to address C extensions using Sulong as it will enable function calls to be inlined when partial evaluation kicks in and let Graal deal with GC. Sulong interpret LLVM IR in a way that enable GC to collect information about objects allocation and release.
Similar to Jython, Zippy has no GIL and can fully make use of multiprocessor systems.

**Comment by oroppas** [comment]
That approach is indeed interesting and different from JyNI.
It appears Graal + Sulong and JyNI are orthogonal.
Any pros and cons of each approach?

**Comment by qunaibit** [comment]
I don't know how JyNI works under the hood but it will be interesting to map a comparison.

**Comment by oroppas** [comment]
Okay. Thanks.
